Making docs a bit more visible
elastic/terraform-provider-ec pull request #152
Opened 2020-10-26 12:40 UTC by Kushmaro

## Description
Changing index.md to readme.md so it's being auto-displayed by Github.
Also linking from the main README to the docs section.

## Motivation and Context
Making docs more visible.

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation

2020-10-26 13:45 UTC, alaudazzi commented on README.md
> +Full resource documentation can be [found here](https://github.com/elastic/terraform-provider-ec/tree/master/docs)
```suggestion
You can find the full resource documentation in the [terraform-provider-ec/docs/](https://github.com/elastic/terraform-provider-ec/tree/master/docs) repo.
```

2020-10-26 13:45 UTC, alaudazzi approved these changes
A minor editing suggestion, otherwise LGTM.

2020-10-27 02:58 UTC, karencfv reviewed
Thanks for the PR @Kushmaro! 

According to the terraform provider registry [requirements](https://www.terraform.io/docs/registry/providers/docs.html#format), we need to have the index page named `index.md`  instead of `README.md` for it to show up properly in the registry documentation. Could you set the name of the file back please? :)

2020-10-27 04:41 UTC, marclop requested changes
I'd just add the link in the main `README.md` pointing to the `index.md`. If. we wanted any "Index" on the `docs` folder, then we can add a separate `README.md`, but as Karen mentions, the TF provider documentation states that an `index.md` is required to publish the docs in the registry.

2020-10-27 09:35 UTC, Kushmaro commented
Thanks @marclop @karencfv , didn't know this was a TF requirement, I've changed the file back as requested

2020-10-27 13:32 UTC, marclop approved these changes

2020-10-28 00:52 UTC, karencfv approved these changes
Thank you!

2020-10-28 05:13 UTC, merged