Adding setting for curation
elastic/terraform-provider-ec pull request #167
Opened 2020-11-04 03:02 UTC by ggsood

The PR is a feature switch for enabling and disabling curation settings for elasticsearch deployments, this is useful when deployment template category is of type hot warm.

Also as curation is deprecated in the future releases having this safety check enables current deployments to easily transition to ILM till the Templates are updated.

This PR will address issue https://github.com/elastic/terraform-provider-ec/issues/166

## How Has This Been Tested?
 - [x] Unit tests and linting is passed
 - [x] Create and update deployments on EC

## Readiness Checklist
 - [x] My code follows the code style of this project
 - [x] My change requires a change to the documentation
 - [ ] I have updated the documentation accordingly, will do once change is reviewed
 - [x] All new and existing tests passed

2020-11-04 03:02 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-11-05 02:17 UTC, karencfv requested changes
First of all thank you @ggsood for finding this bug and opening a PR to fix it 🎉 👏 

I'd like to change the approach to the solution though.

We want to keep the Schema as simple as possible so adding a new argument to the top level to account for a case that is only really necessary for Hot Warm deployments, would kind of move us toward the opposite direction.

Second, as this is a new product that hasn't been released yet, we also do not want to support things that are on their way to being deprecated (as you can tell, on the UI you can't create new hot-warm deployments with curation based settings). 

An approach that aligns with these two statements would be as follows:

- Handle setting empty curation settings within the Elasticsearch expanders.
- Modify the documentation on importing to include a warning note explaining how only ILM Hot Warm deployments are supported.

Like this:
```console
$ git diff
diff --git a/docs/resources/ec_deployment.md b/docs/resources/ec_deployment.md
index 283255e..e133900 100644
--- a/docs/resources/ec_deployment.md
+++ b/docs/resources/ec_deployment.md
@@ -304,6 +304,8 @@ In addition to all arguments above, the following attributes are exported:
 
 ~> **Note on legacy (pre-slider) deployments** If your deployment was created prior to the addition of sliders in both ECE or ESS, and has not been migrated to use sliders, importing it is not supported and will result in erroneous behavior.
 
+~> **Note on pre ILM Hot Warm deployments** If your deployment uses Index Curation, you will have to migrate to Index Lifecycle Management (ILM) before importing. Index Curation will be deprecated soon and is not supported in the provider.
+
 Deployments can be imported using the `id`, e.g.
 
diff --git a/ec/ecresource/deploymentresource/elasticsearch_expanders.go b/ec/ecresource/deploymentresource/elasticsearch_expanders.go
index 6e938d0..7fc5006 100644
--- a/ec/ecresource/deploymentresource/elasticsearch_expanders.go
+++ b/ec/ecresource/deploymentresource/elasticsearch_expanders.go
@@ -21,6 +21,7 @@ import (
        "encoding/json"
        "fmt"
        "reflect"
+       "strings"
 
        "github.com/elastic/cloud-sdk-go/pkg/models"
        "github.com/elastic/cloud-sdk-go/pkg/util/ec"
@@ -65,6 +66,11 @@ func expandEsResource(raw interface{}, res *models.ElasticsearchPayload) (*model
                }
        }
 
+       // This is necessary as the default Elasticsearch payload
+       // for hot warm deployments still enables curation based
+       // settings which will soon be deprecated.
+       res = setEmptyCuration(*res.Plan.DeploymentTemplate.ID, res)
+
        if rt, ok := es["topology"]; ok && len(rt.([]interface{})) > 0 {
                topology, err := expandEsTopology(rt, res.Plan.ClusterTopology)
                if err != nil {
@@ -229,3 +235,12 @@ func esResource(res *models.DeploymentTemplateInfoV2) *models.ElasticsearchPaylo
        }
        return res.DeploymentTemplate.Resources.Elasticsearch[0]
 }
+
+func setEmptyCuration(template string, esPayload *models.ElasticsearchPayload) *models.ElasticsearchPayload {
+       if strings.Contains(template, "hot-warm") {
+               esPayload.Plan.Elasticsearch.Curation = nil
+               esPayload.Settings.Curation = nil
+       }
+
+       return esPayload
+}
diff --git a/ec/ecresource/deploymentresource/expanders.go b/ec/ecresource/deploymentresource/expanders.go
index 08ad33f..b724d8a 100644
--- a/ec/ecresource/deploymentresource/expanders.go
+++ b/ec/ecresource/deploymentresource/expanders.go
@@ -93,11 +93,6 @@ func createResourceToModel(d *schema.ResourceData, client *api.API) (*models.Dep
        }
        result.Settings.Observability = observability
 
-       if d.Get("disable_curation").(bool) && len(result.Resources.Elasticsearch) > 0 {
-               result.Resources.Elasticsearch[0].Plan.Elasticsearch.Curation = nil
-               result.Resources.Elasticsearch[0].Settings.Curation = nil
-       }
-
        return &result, nil
 }
 
@@ -184,10 +179,6 @@ func updateResourceToModel(d *schema.ResourceData, client *api.API) (*models.Dep
                result.Settings.Observability = &models.DeploymentObservabilitySettings{}
        }
 
-       if d.Get("disable_curation").(bool) && len(result.Resources.Elasticsearch) > 0 {
-               result.Resources.Elasticsearch[0].Plan.Elasticsearch.Curation = nil
-               result.Resources.Elasticsearch[0].Settings.Curation = nil
-       }
        return &result, nil
 }
 
diff --git a/ec/ecresource/deploymentresource/schema.go b/ec/ecresource/deploymentresource/schema.go
index c7c797c..d19a475 100644
--- a/ec/ecresource/deploymentresource/schema.go
+++ b/ec/ecresource/deploymentresource/schema.go
@@ -59,12 +59,6 @@ func newSchema() map[string]*schema.Schema {
                        Description: "Optional request_id to set on the create operation, only use when previous create attempts return with an error and a request_id is returned as part of the error",
                        Optional:    true,
                },
-               "disable_curation": {
-                       Type:        schema.TypeBool,
-                       Description: "Optional disable curation settings in case of hot-warm to enable ILM settings",
-                       Optional:    true,
-                       Default:     false,
-               },
 
                // Computed ES Creds
                "elasticsearch_username": {
```

2020-11-05 12:41 UTC, ggsood commented
Thanks @karencfv for the review, have corrected the code and unit tests, please can you check.

2020-11-05 22:09 UTC, karencfv commented
Jenkins test this please

2020-11-06 05:02 UTC, karencfv approved these changes
Thank you @ggsood ! 🙇‍♀️

2020-11-06 05:04 UTC, merged